name: Create ENV File
description: Creates a .env file with specified variables
inputs:
  filepath:
    description: Path to create .env file
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        cat <<EOF > ${{ inputs.filepath }}
        AB_CLIENT_ID=${{ secrets.AB_CLIENT_ID }}
        AB_CLIENT_SECRET=${{ secrets.AB_CLIENT_SECRET }}
        AB_USERNAME=${{ secrets.AB_USERNAME }}
        AB_PASSWORD=${{ secrets.AB_PASSWORD }}
        TRINT_API_KEY=${{ secrets.TRINT_API_KEY }}
        ELASTICSEARCH_HOST=${{ secrets.ELASTICSEARCH_HOST }}
        ELASTICSEARCH_API_KEY=${{ secrets.ELASTICSEARCH_API_KEY }}
        SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }}
        EOF
