name: "PHP project"

description: "Setup the project environment and dependencies"

inputs:
  php-version:
    description: "The PHP version to install"
    required: true
    default: "8.3"

runs:
  using: composite

  steps:
    ###
    # Configure PHP environment
    ###

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}

    ###
    # Install backend application dependencies
    ###

    - name: Get composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer packages
      shell: bash
      run: composer --prefer-dist --no-progress --no-suggest install
